#!/bin/bash
xrdb ~/.Xresources

# Run the screen compositor
picom &

# Change keyword layout.
remap &

# Enable screen locking on suspend
xss-lock -- slock &

# Fire it up
#exec dbus-launch --exit-with-session emacs -mm --debug-init -l ~/.config/emacs/init.el
